<a href="https://colab.research.google.com/github/Te-Os/capstone1.resume-html/blob/main/Tensors_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [19]:
import torch
import numpy as np

In [4]:
v = torch.tensor([1,2,3])
print(v.dtype)

torch.int64


In [8]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [10]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f)
print(f.dtype)
print(f.size() )

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])


In [17]:
v.view(6,1)


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [18]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [21]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [24]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)


[1 2 3 4 5]
